# Site settings
title:          Transcription typémique sur l’écriture de L. Meigret (1500-1558)
description:    "Pour une philologie progressive des textes grammaticaux et orthographistes de Louis Meigret (1500 ca -1558 ca)"

url:            "https://github.com/xinyucindy/tale"

# Author
author:
  name:         Cindy YU
  url:          néant
  email:        xinyu.cindy25@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
